package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.Toast;
//import java.lang.Math;

import com.example.myapplication.databinding.ActivityMainBinding;

public class MainActivity extends AppCompatActivity {

    //you cannot use a Binding until you add the following lines to the
    // Android section of the build.gradle(Module) file (under the
    // compileSDK line is fine) and then resync gradle files
    //    buildFeatures {
    //        viewBinding = true
    //    }

    // The name of the binding class is generated by converting the
    // name of the XML file to Pascal case and adding the word "Binding"
    // to the end. Similarly, the reference for each view is generated
    // by removing underscores and converting the view name to camel
    // case. For example, in Pascal case activity_main.xml becomes
    // ActivityMainBinding, and you can access @id/text_view as
    // binding.textView.
    private ActivityMainBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding=ActivityMainBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        //use above instead of the following
        //setContentView(R.layout.activity_main);

        //add an anonymous onclick listener (as opposed to doing it in XML)
        binding.calculateButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                calculateTip();
            }
        });
    }

    private void calculateTip() {
        //wrap in a try in case user trys to calc tip with no cost entered
        try {
            double cost = Double.parseDouble(binding.costOfService.getText().toString());

            //get selected radio button
            int id = binding.tipOptions.getCheckedRadioButtonId();

            //get tip amount
            Double tip=0.0;
            switch(id){
                case R.id.option_twenty_percent:
                    tip=0.2;
                    break;
                case R.id.option_eighteen_percent:
                    tip=0.18;
                    break;
                default:
                    tip=0.15;
            }
            Double tots = cost*tip;

            //do we round up?
            if(binding.idRoundup.isChecked())
                tots=Math.ceil(tots);

            binding.tipResult.setText(String.valueOf(tots));
        }catch (RuntimeException ex){
            Toast.makeText(MainActivity.this,"Please enter a Cost!",Toast.LENGTH_SHORT).show();
            return;
        }
    }
}